name: Create Release

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release from pyproject version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '22'


      - name: 🏷️ Get version from package.json
        id: get_version
        run: |
          version=$(node -p "require('./package.json').version")
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: 🔍 Check if release exists
        id: check_release
        shell: bash
        run: |
          VERSION="v${{ steps.get_version.outputs.version }}"
          echo "Checking for release $VERSION..."
          if gh release view "$VERSION" 2>/dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ❌ Cancel workflow if release exists
        if: steps.check_release.outputs.exists == 'true'
        run: |
          echo "Release v${{ steps.get_version.outputs.version }} already exists. Cancelling workflow."
          exit 0

      - name: Install packages
        if: steps.check_release.outputs.exists == 'false'
        run: |
          npm ci

      - name: Build project
        if: steps.check_release.outputs.exists == 'false'
        run: |
          npm run build
          cp src/scripts/* ./dist/
          cp src/utils/install* ./dist/
          echo "${{ steps.get_version.outputs.version }}" > ./dist/VERSION

      - name: Create GitHub Release and upload payload
        if: steps.check_release.outputs.exists == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.get_version.outputs.version }}"
          name: "v${{ steps.get_version.outputs.version }}"
          body: |
            ## Installation commands
            
            Windows (PowerShell):
            ```powershell
            iwr -useb https://github.com/XXanderWP/TerminalUtils/releases/download/v${{ steps.get_version.outputs.version }}/install.ps1 | iex
            ``` 

            Linux/macOS (Bash):
            ```bash
            curl -fsSL https://github.com/XXanderWP/TerminalUtils/releases/download/v${{ steps.get_version.outputs.version }}/install.sh | bash
            ```
          files: dist/*
